name: Build and Deploy

on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.1
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: bbengamin/bakery-delivery:${{ steps.commit.outputs.short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/config/Dockerfile.prod
          build-args: |
            VUE_APP_MAPBOX_API_KEY=${{ secrets.VUE_APP_MAPBOX_API_KEY }}
            VUE_APP_API_URL=${{ vars.VUE_APP_API_URL }}
            VUE_APP_FLAGSMITH_URL=${{ vars.VUE_APP_FLAGSMITH_URL }}
            VUE_APP_FLAGSMITH_API_KEY=${{ secrets.VUE_APP_FLAGSMITH_API_KEY }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          script: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
            docker pull bbengamin/bakery-delivery:${{ steps.commit.outputs.short }}
            docker stop bakery-delivery
            docker rm bakery-delivery
            
            docker run --name bakery-delivery \
              -e APP_PORT=2000 \
              -e VUE_APP_API_URL=${{ vars.VUE_APP_API_URL }} \
              -e VUE_APP_MAPBOX_API_KEY=${{ secrets.VUE_APP_MAPBOX_API_KEY }} \
              -p ${{ vars.APP_PORT }}:80 \
              --restart unless-stopped \
              -d \
              bbengamin/bakery-delivery:${{ steps.commit.outputs.short }}
